export const texts = {
	users: "users",
	yes: "yes",
	no: "no",
	good: "good",
	bad: "bad",
	medium: "medium",
	streak: "streak",
	last: "last repeat",
	percent: "percent of good repeats",
	source: "source word",
	target: "translation",
	part: "part of speech",
	user: {
		do: "what do you want to do?",
	},
	form: {
		sourcePlaceholder: "Add word",
		targetPlaceholder: "Add translation",
		noun: "Noun",
		verb: "Verb",
		adverb: "Adverb",
		pronoun: "Pronoun",
		adjective: "Adjective",
		sentence: "Sentence",
		submit: "submit",
		notesPlaceholder: "Enter your notes here...",
	},
	repeats: {
		title: "repeats",
		show: "show",
		nothing: "nothing to repeat",
	},
	login: {
		choose: "choose your profile",
		go: "login",
	},
	header: {
		words: "your words",
		repeats: "repeats for today",
		add: "add word",
		hi: "hello",
	},
	words: {
		remove: "Do you want to remove word?",
		sourceLang: "source language",
		targetLang: "target language",
		next: "next repeat",
		notes: "notes",
		delete: "delete",
	},
};
